#!/usr/bin/env python

import urllib
import json
import sys
import os.path
from os.path import expanduser
from subprocess import call

home = expanduser("~")
config_exists = os.path.isfile(home + '/.cmnd') 

def setup():
  config_file = open(home + '/.cmnd', 'w')
  config_file.write("Hello!")
  raw_input("We'll need to open a browser to http://cmnd.center so you can authorize this client. Press enter.")
  call(["open", "http://localhost:3001/api/commands"])

def command():
  print "command"
  config_file.close()

if not config_exists or len(sys.argv) == 1 or sys.argv[1] == "setup":
  setup()
elif config_exists:
  config_file = open(home + '/.cmnd', 'r')
  access_token = config_file.read()
  print access_token
  if len(access_token) != 256:
    config_file.close()
    setup()
  else:
    command(config_file)