#!/usr/bin/env python

import urllib
import urllib2
import json
import sys
import os.path
import base64
from os.path import expanduser
from subprocess import call

home = expanduser("~")
config_exists = os.path.isfile(home + '/.cmnd') 
domain = "https://cmnd.center"

def setup():
  config_file = open(home + '/.cmnd', 'w')
  username = raw_input("We need to authenticate first. What is your username?\n")
  password = raw_input("And your password?\n")

  request = urllib2.Request(domain + "/api/oauth2/native/54a1fbe9a09c17c47e1e8ec5")
  base64string = base64.encodestring('%s:%s' % (username, password)).replace('\n', '')
  config_file.write(base64string)
  config_file.close()
  print "Authentication hash saved. You may now issue commands."

def command(base64string):
  command = {}
  start = 1
  print_json = False
  if sys.argv[1] == "-j":
    start = 2
    print_json = True
  command['command_word'] = sys.argv[start];
  command['message'] = (' ').join(sys.argv[start+1:])
  req = urllib2.Request(domain + "/api/commands")
  req.add_header('Authorization', 'Basic ' + basicAuthString)
  req.add_data(urllib.urlencode(command))

  try:
    response = urllib2.urlopen(req)
  except urllib2.HTTPError, e:
    if e.code == 401:
      setup()
      return
    else:
      print e.code
      print e
      return
  
  obj = json.loads(response.read())
  if print_json:
    print json.dumps(obj, indent=2, separators=(',', ': '))
  else:
    print json.dumps(obj, indent=0, separators=(',', ': '))[2:-2].replace('\"','')
  response.close()

if not config_exists or len(sys.argv) == 1 or sys.argv[1] == "setup":
  setup()
elif config_exists:
  config_file = open(home + '/.cmnd', 'r')
  base64string = config_file.read()
  config_file.close()
  command(base64string)